### ISSUE TITLE
1.7.10 LlittleMaidMobX crash

### ISSUE THREAD

**Issue by RsFlux1710** [makamys/MAtmos#12]
With matmos-1.7.10-35.4.1 and littleMaidMobX-1.7.x_0.1.1, minecraft,  crashes upon launch .
Is this possible to fix it? I'm sorry my bad English.

version : forge-1.7.10-10.13.4.1614
mods   : matmos-1.7.10-35.4.1,  littleMaidMobX-1.7.x_0.1.1
↓↓↓↓↓↓↓↓↓↓crash report↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓
Description: There was a severe problem during mod loading that has caused the game to fail

cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: org/jetbrains/java/decompiler/main/extern/IResultSaver
	at cpw.mods.fml.common.LoadController.transition(LoadController.java:163)
	at cpw.mods.fml.common.Loader.initializeMods(Loader.java:744)
	at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:311)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:552)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NoClassDefFoundError: org/jetbrains/java/decompiler/main/extern/IResultSaver
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:106)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at mmmlibx.lib.multiModel.texture.MultiModelManager.addModelClass(MultiModelManager.java:103)
	at mmmlibx.lib.multiModel.texture.MultiModelManager.load(MultiModelManager.java:79)
	at mmmlibx.lib.FileLoaderBase.preLoad(FileLoaderBase.java:107)
	at mmmlibx.lib.FileLoaderBase.decodeZip(FileLoaderBase.java:52)
	at mmmlibx.lib.multiModel.texture.MultiModelManager.decodeZip(MultiModelManager.java:71)
	at mmmlibx.lib.FileLoaderBase.execute(FileLoaderBase.java:27)
	at mmmlibx.lib.multiModel.texture.MultiModelManager.execute(MultiModelManager.java:63)
	at mmmlibx.lib.MMMLib.loaded(MMMLib.java:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
	at sun.reflect.GeneratedMethodAccessor5.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
	at cpw.mods.fml.common.Loader.initializeMods(Loader.java:742)
	... 10 more
Caused by: java.lang.ClassNotFoundException: org.jetbrains.java.decompiler.main.extern.IResultSaver
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 59 more

A detailed walkthrough of the error, its code path and all known details is as follows:

**Comment by makamys** [comment]
LittleMaidMobX does some really weird stuff: it loads every single class in every single mod in order to find models. The crash happens because it loaded a class that was not supposed to be loaded.

The only thing I could do about this would be to release a version of MAtmos without Mixins (which is what MAtmos uses to work around Minecraft's buggy sound manager), but that would come with the downside of buggy sound playback. Since I don't find it acceptable to knowingly release software with bugs, I'm not going to do that.

The only real fix for this would be to get someone to release a modified version of LittleMaidMobX that doesn't have this bug.

**Comment by makamys** [comment]
Actually I just realized there's a fork of LMMX that doesn't have this issue. Try it!
https://github.com/Goujer/LittleMaidMobEnhanced

**Comment by huihiuhuai** [comment]
enhanced dont compatible with shaders

**Comment by huihiuhuai** [comment]
enhanced version gui dont compatible with shaders
