### ISSUE TITLE
Matmos crashed on startup due to digital miner from mekanism

### ISSUE THREAD

**Issue by Star4Fun** [makamys/MAtmos#8]
When I start my map the game crashes. To fix it I removed Matmos, DynamicSurroundings and SoundFilters. I broke the digital miner and now the world launches without problems. Without the digital miner the mods are working too.

`
java.lang.NullPointerException: Ticking block entity
	at eu.ha3.mc.haddon.forge.ForgeBase.onBlock(ForgeBase.java:191)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_957_ForgeBase_onBlock_BlockEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at mekanism.common.tile.TileEntityDigitalMiner.canMine(TileEntityDigitalMiner.java:366)
	at mekanism.common.tile.TileEntityDigitalMiner.onUpdate(TileEntityDigitalMiner.java:230)
	at mekanism.common.tile.prefab.TileEntityBasicBlock.func_73660_a(TileEntityBasicBlock.java:86)
	at net.minecraft.world.World.func_72939_s(World.java:1838)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:252)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Unknown Source)
`

**Comment by makamys** [comment]
Which version of Minecraft and Mekanism were you using?

**Comment by Star4Fun** [comment]
Mekanism-1.12.2-9.8.3.390 and Matmos-1.12.2-35.2

**Comment by Star4Fun** [comment]
The same thing happened with the crop breaker from Industrial Foregoing. (Version: industrialforegoing-1.12.2-1.12.13-237)

`
java.lang.NullPointerException: Ticking block entity
	at eu.ha3.mc.haddon.forge.ForgeBase.onBlock(ForgeBase.java:191)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_970_ForgeBase_onBlock_BlockEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at com.github.terminatornl.laggoggles.tickcentral.EventBusTransformer.redirectEvent(EventBusTransformer.java:67)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at com.buuz135.industrial.utils.BlockUtils.canBlockBeBroken(BlockUtils.java:99)
	at com.buuz135.industrial.tile.agriculture.CropRecolectorTile.work(CropRecolectorTile.java:109)
	at com.buuz135.industrial.tile.WorkingAreaElectricMachine.performWork(WorkingAreaElectricMachine.java:112)
	at net.ndrei.teslacorelib.tileentities.ElectricMachine.protectedUpdate(ElectricMachine.kt:280)
	at com.buuz135.industrial.tile.CustomElectricMachine.protectedUpdate(CustomElectricMachine.java:120)
	at net.ndrei.teslacorelib.tileentities.ElectricTileEntity.innerUpdate(ElectricTileEntity.kt:118)
	at net.ndrei.teslacorelib.tileentities.SidedTileEntity.TickCentral_TrueITickableUpdate(SidedTileEntity.kt:991)
	at com.github.terminatornl.tickcentral.api.TickHub.trueUpdate(TickHub.java:48)
	at com.github.terminatornl.laggoggles.Main.redirectUpdate(Main.java:91)
	at net.ndrei.teslacorelib.tileentities.SidedTileEntity.func_73660_a(SidedTileEntity.kt)
	at net.minecraft.world.World.func_72939_s(World.java:1838)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:252)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Unknown Source)
`

**Comment by makamys** [comment]
Adding a null check fixed it.
